version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ./data:/data
    ports:
      - "3001:3001"
    restart: always

  sqlite:
    image: nouchka/sqlite3
    platform: linux/amd64
    container_name: sqlite
    volumes:
      - ./data:/app/data
    working_dir: /app/data
    entrypoint: ["sh"]
    tty: true
